[ds]
name = "DS"
doperoms = "Nintendo_Ds"
image = "res/ds.png"
roms = "roms/ds"
program = "desmume"
args = ["%r"]

[gamecube]
name = "Gamecube"
doperoms = "Nintendo_Gamecube"
image = "res/gamecube.png"
roms = "roms/gamecube"
program = "dolphin-emu"
args = ["-b", "-e", "%r"]

[gba]
name = "Gameboy Advance"
doperoms = "Gameboy_Advance_Gba"
image = "res/gba.png"
roms = "roms/gba"
program = "vba"
args = ["-F", "%r"]

[gbc]
name = "Gameboy Color"
doperoms = "Gameboy_And_Gbc"
image = "res/gbc.png"
roms = "roms/gbc"
program = "vba"
args = ["-F", "%r"]

[n64]
name = "Nintendo 64"
doperoms = "Nintendo_64"
image = "res/n64.png"
roms = "roms/n64"
program = "mupen64plus"
args = ["--fullscreen", "%r"]

[nes]
name = "NES"
doperoms = "Nintendo_Nes"
image = "res/nes.png"
roms = "roms/nes"
program = "nestopia"
args = ["-f", "%r"]

[snes]
name = "SNES"
doperoms = "Super_Nintendo_Snes"
image = "res/snes.png"
roms = "roms/snes"
program = "zsnes"
args = ["%r"]

[wii]
name = "Wii"
doperoms = "Nintendo_Wii"
image = "res/wii.png"
roms = "roms/wii"
program = "dolphin-emu"
args = ["-b", "-e", "%r"]
