[ds]
name = "DS"
program = "desmume"
args = ["%r"]
image = "res/ds.png"

[gamecube]
name = "Gamecube"
program = "dolphin-emu"
args = ["-b", "-e", "%r"]
image = "res/gamecube.png"

[gba]
name = "Gameboy Advance"
program = "vba"
args = ["-F", "%r"]
image = "res/gba.png"

[gbc]
name = "Gameboy Color"
program = "vba"
args = ["-F", "%r"]
image = "res/gbc.png"

[n64]
name = "Nintendo 64"
program = "mupen64plus"
args = ["--fullscreen", "%r"]
image = "res/n64.png"

[nes]
name = "NES"
program = "nestopia"
args = ["-f", "%r"]
image = "res/nes.png"

[snes]
name = "SNES"
program = "zsnes"
args = ["%r"]
image = "res/snes.png"

[wii]
name = "Wii"
program = "dolphin-emu"
args = ["-b", "-e", "%r"]
image = "res/wii.png"
