[ds]
name = "DS"
image = "res/ds.png"
roms = "roms/ds"
program = "desmume"
args = ["%r"]

[gamecube]
name = "Gamecube"
image = "res/gamecube.png"
roms = "roms/gamecube"
program = "dolphin-emu"
args = ["-b", "-e", "%r"]

[gba]
name = "Gameboy Advance"
image = "res/gba.png"
roms = "roms/gba"
program = "vba"
args = ["-F", "%r"]

[gbc]
name = "Gameboy Color"
image = "res/gbc.png"
roms = "roms/gbc"
program = "vba"
args = ["-F", "%r"]

[n64]
name = "Nintendo 64"
image = "res/n64.png"
roms = "roms/n64"
program = "mupen64plus"
args = ["--fullscreen", "%r"]

[nes]
name = "NES"
image = "res/nes.png"
roms = "roms/nes"
program = "nestopia"
args = ["-f", "%r"]

[snes]
name = "SNES"
image = "res/snes.png"
roms = "roms/snes"
program = "zsnes"
args = ["%r"]

[wii]
name = "Wii"
image = "res/wii.png"
roms = "roms/wii"
program = "dolphin-emu"
args = ["-b", "-e", "%r"]
